import Head from 'next/head'

import { ContentClock } from '@/Components/ContentClock'

export default function Home() {
  return (
    <>
      <Head>
        <title>Clock nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentClock/>
     
     
    </>
  )
}
